```mermaid
---
title: Before Rebase
---
gitGraph
    commit id: "SHA-1"
    commit id: "SHA-2"
    branch feature
    checkout feature
    commit id: "SHA-5"
    commit id: "SHA-6"
    checkout main
    commit id: "SHA-3"
    commit id: "SHA-4"
```

```mermaid
---
title: After Rebase
---
gitGraph
    commit id: "SHA-1"
    commit id: "SHA-2"
    commit id: "SHA-3"
    commit id: "SHA-4"
    branch feature
    checkout feature
    commit id: "SHA-7"
    commit id: "SHA-8"
```